# Insert a password hash to enable password protection for this directory
# Use one of the following commands to create a hash:
#   mkpasswd -m sha-256
#   mkpasswd -m sha-512
#
hashed_password = "$5$s9bLebSgS9O4CPDR$xQF4/bWQqv5rqaq3Or2oTpXBW4TZdjFtBeH9CwZiw72" # movie_night!

# Set this to 'true' to allow file downloads from this directory
download = true

# Set this to 'true' to allow uploads to this directory
upload = false