# Insert a password hash to enable password protection for this directory
# Use one of the following commands to create a hash:
#   mkpasswd -m sha-256
#   mkpasswd -m sha-512
#
#hashed_password = ""

# Set this to 'true' to allow file downloads from this directory
download = false

# Set this to 'true' to allow uploads to this directory
upload = true